name: lbe_admin_manager
description: "Admin app for lbe helmets"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4
dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^3.0.0
  process_run: ^0.12.0
  cupertino_icons: ^1.0.8
  flet: ^0.25.1
  http: ^1.2.2
  file_picker: ^8.1.4
  network_info_plus: ^5.0.2
  get_ip_address: ^0.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/